"""Initial schema with dream_entries table

Revision ID: aa773922106b
Revises: 
Create Date: 2025-10-31 16:08:09.615663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa773922106b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create journal schema if it doesn't exist
    op.execute('CREATE SCHEMA IF NOT EXISTS journal')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dream_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('saved_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='journal'
    )
    op.create_index('idx_dream_entries_uploaded_at', 'dream_entries', ['uploaded_at'], unique=False, schema='journal')
    op.create_index(op.f('ix_journal_dream_entries_saved_filename'), 'dream_entries', ['saved_filename'], unique=True, schema='journal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_dream_entries_saved_filename'), table_name='dream_entries', schema='journal')
    op.drop_index('idx_dream_entries_uploaded_at', table_name='dream_entries', schema='journal')
    op.drop_table('dream_entries', schema='journal')
    # ### end Alembic commands ###

    # Drop journal schema (CASCADE removes all objects in the schema)
    op.execute('DROP SCHEMA IF EXISTS journal CASCADE')
