"""Initial schema with voice_entries table

Revision ID: aa773922106b
Revises:
Create Date: 2025-10-31 16:08:09.615663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from schema_config import get_schema


# revision identifiers, used by Alembic.
revision: str = 'aa773922106b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    schema = get_schema()
    # Ensure schema exists
    # This is safe to run even if user lacks CREATE SCHEMA privilege
    # because we check for existence first (only requires SELECT on information_schema)
    from sqlalchemy import text
    conn = op.get_bind()
    result = conn.execute(text(
        f"SELECT schema_name FROM information_schema.schemata WHERE schema_name = '{schema}'"
    ))
    if not result.fetchone():
        # Only attempt creation if schema doesn't exist
        # In production: schema should already exist (created by DBA)
        # In development: this creates it automatically
        conn.execute(text(f'CREATE SCHEMA "{schema}"'))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('saved_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('entry_type', sa.String(length=50), nullable=False, server_default='dream'),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema=schema
    )
    op.create_index('idx_voice_entries_uploaded_at', 'voice_entries', ['uploaded_at'], unique=False, schema=schema)
    op.create_index('idx_voice_entries_entry_type', 'voice_entries', ['entry_type'], unique=False, schema=schema)
    op.create_index(op.f('ix_journal_voice_entries_saved_filename'), 'voice_entries', ['saved_filename'], unique=True, schema=schema)
    # ### end Alembic commands ###


def downgrade() -> None:
    schema = get_schema()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_voice_entries_saved_filename'), table_name='voice_entries', schema=schema)
    op.drop_index('idx_voice_entries_entry_type', table_name='voice_entries', schema=schema)
    op.drop_index('idx_voice_entries_uploaded_at', table_name='voice_entries', schema=schema)
    op.drop_table('voice_entries', schema=schema)
    # ### end Alembic commands ###

    # Schema deletion commented out for safety
    # In production: DBA should drop schema manually if needed
    # op.execute(f'DROP SCHEMA IF EXISTS {schema} CASCADE')
