"""add_users_table

Revision ID: c6459d14db37
Revises: b1c2d3e4f5a6
Create Date: 2025-11-09 18:56:20.170733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from schema_config import get_schema


# revision identifiers, used by Alembic.
revision: str = 'c6459d14db37'
down_revision: Union[str, None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    schema = get_schema()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema=schema
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False, schema=schema)
    op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False, schema=schema)
    op.create_index(op.f('ix_journal_users_email'), 'users', ['email'], unique=True, schema=schema)
    op.drop_index('idx_transcriptions_entry_id', table_name='transcriptions', schema=schema)
    op.drop_index('idx_transcriptions_is_primary', table_name='transcriptions', schema=schema)
    op.create_index(op.f('ix_journal_transcriptions_entry_id'), 'transcriptions', ['entry_id'], unique=False, schema=schema)
    op.create_index(op.f('ix_journal_transcriptions_is_primary'), 'transcriptions', ['is_primary'], unique=False, schema=schema)
    op.create_index(op.f('ix_journal_transcriptions_status'), 'transcriptions', ['status'], unique=False, schema=schema)
    op.create_index(op.f('ix_journal_voice_entries_entry_type'), 'voice_entries', ['entry_type'], unique=False, schema=schema)
    # ### end Alembic commands ###


def downgrade() -> None:
    schema = get_schema()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_voice_entries_entry_type'), table_name='voice_entries', schema=schema)
    op.drop_index(op.f('ix_journal_transcriptions_status'), table_name='transcriptions', schema=schema)
    op.drop_index(op.f('ix_journal_transcriptions_is_primary'), table_name='transcriptions', schema=schema)
    op.drop_index(op.f('ix_journal_transcriptions_entry_id'), table_name='transcriptions', schema=schema)
    op.create_index('idx_transcriptions_is_primary', 'transcriptions', ['is_primary'], unique=False, schema=schema)
    op.create_index('idx_transcriptions_entry_id', 'transcriptions', ['entry_id'], unique=False, schema=schema)
    op.drop_index(op.f('ix_journal_users_email'), table_name='users', schema=schema)
    op.drop_index('idx_users_is_active', table_name='users', schema=schema)
    op.drop_index('idx_users_email', table_name='users', schema=schema)
    op.drop_table('users', schema=schema)
    # ### end Alembic commands ###
